name: bookbuddy
description: "BookBuddy - Discover and save books using Google Books API."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # State Management
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  equatable: ^2.0.5

  # Navigation
  go_router: ^14.2.0

  # Network
  dio: ^5.7.0

  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Dependency Injection
  get_it: ^8.0.0

  # Functional Programming (Either)
  dartz: ^0.10.1

  # Image Caching
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
